# Generated by Django 5.0.6 on 2024-06-11 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('salary', models.CharField(max_length=100)),
                ('number_of_openings', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('education', 'Education'), ('Medical', 'Medical'), ('Design', 'Design'), ('Developer', 'Developer')], max_length=40, null=True)),
                ('job_description', models.TextField(null=True)),
                ('skills', models.CharField(max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobseekerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.TextField()),
                ('experience', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='static/media')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seekermodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='static/media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitermodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
