# Generated by Django 5.0.6 on 2024-06-11 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_jobmodel_jobseekermodel_recruitermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobApplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='media/seeker_resume')),
                ('seeker_profile_pic', models.ImageField(upload_to='media/seeker_profile_pic')),
                ('qualifications', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('date_fix', models.DateField(null=True)),
                ('applicants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applients', to=settings.AUTH_USER_MODEL)),
                ('jobmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.jobmodel')),
            ],
        ),
    ]
